package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/mproyyan/goparcel/internal/common/genproto"
	"github.com/mproyyan/goparcel/internal/graphql/graph/model"
)

// GetMatchingCargos is the resolver for the GetMatchingCargos field.
func (r *queryResolver) GetMatchingCargos(ctx context.Context, origin string, destination string) ([]*model.Cargo, error) {
	result, err := r.cargoService.GetMatchingCargos(ctx, &genproto.GetMatchingCargosRequest{
		Origin:      origin,
		Destination: destination,
	})

	if err != nil {
		fmt.Println("panggil")
		return nil, err
	}

	return cargosToGraphResponse(result.Cargos), nil
}
