package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"
	"strings"

	"github.com/mproyyan/goparcel/internal/common/auth"
	"github.com/mproyyan/goparcel/internal/common/genproto"
	"github.com/mproyyan/goparcel/internal/graphql/graph/generated"
	"github.com/mproyyan/goparcel/internal/graphql/graph/middlewares"
	"github.com/mproyyan/goparcel/internal/graphql/graph/model"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Carriers is the resolver for the carriers field.
func (r *cargoResolver) Carriers(ctx context.Context, obj *model.Cargo) ([]*model.Carrier, error) {
	if obj.ID == "" || obj.Carriers == nil {
		return nil, nil
	}

	var carrierIds []string
	for _, carrier := range obj.Carriers {
		if carrier == nil {
			continue
		}

		carrierIds = append(carrierIds, carrier.ID)
	}

	stringCarrierIds := strings.Join(carrierIds, ",")
	key := fmt.Sprintf("%s:%s", obj.ID, stringCarrierIds)

	return r.carriersLoader.Load(ctx, key)
}

// Shipments is the resolver for the shipments field.
func (r *cargoResolver) Shipments(ctx context.Context, obj *model.Cargo) ([]*model.Shipment, error) {
	if obj.ID == "" || obj.Shipments == nil {
		return nil, nil
	}

	var shipmentIds []string
	for _, shipment := range obj.Shipments {
		if shipment == nil {
			continue
		}

		shipmentIds = append(shipmentIds, shipment.ID)
	}

	stringShipmentIds := strings.Join(shipmentIds, ",")
	key := fmt.Sprintf("%s:%s", obj.ID, stringShipmentIds)

	return r.shipmentsLoader.Load(ctx, key)
}

// LastKnownLocation is the resolver for the last_known_location field.
func (r *cargoResolver) LastKnownLocation(ctx context.Context, obj *model.Cargo) (*model.Location, error) {
	if obj.LastKnownLocation == nil {
		return nil, nil
	}

	if obj.LastKnownLocation.ID == "" {
		return nil, nil
	}

	return r.locationLoader.Load(ctx, obj.LastKnownLocation.ID)
}

// Cargo is the resolver for the cargo field.
func (r *carrierResolver) Cargo(ctx context.Context, obj *model.Carrier) (*model.Cargo, error) {
	if obj.Cargo == nil {
		return nil, nil
	}

	if obj.Cargo.ID == "" {
		return nil, nil
	}

	return r.cargoLoader.Load(ctx, obj.Cargo.ID)
}

// Location is the resolver for the location field.
func (r *carrierResolver) Location(ctx context.Context, obj *model.Carrier) (*model.Location, error) {
	if obj.Location == nil {
		return nil, nil
	}

	if obj.Location.ID == "" {
		return nil, nil
	}

	return r.locationLoader.Load(ctx, obj.Location.ID)
}

// Location is the resolver for the location field.
func (r *itineraryResolver) Location(ctx context.Context, obj *model.Itinerary) (*model.Location, error) {
	if obj.Location == nil {
		return nil, nil
	}

	if obj.Location.ID == "" {
		return nil, nil
	}

	return r.locationLoader.Load(ctx, obj.Location.ID)
}

// LoadShipment is the resolver for the LoadShipment field.
func (r *mutationResolver) LoadShipment(ctx context.Context, shipmentID string, locationID string) (string, error) {
	authUser, err := middlewares.GetAuthUser(ctx)
	if err != nil {
		return "", err
	}

	ctx = auth.SendAuthUser(ctx, authUser.UserID, authUser.ModelID)
	_, err = r.cargoService.LoadShipment(ctx, &genproto.LoadShipmentRequest{
		LocationId: locationID,
		ShipmentId: shipmentID,
	})

	if err != nil {
		return "", err
	}

	return "shipment loaded successfully", nil
}

// MarkArrival is the resolver for the MarkArrival field.
func (r *mutationResolver) MarkArrival(ctx context.Context, cargoID string, locationID string) (string, error) {
	_, err := r.cargoService.MarkArrival(ctx, &genproto.MarkArrivalRequest{
		CargoId:    cargoID,
		LocationId: locationID,
	})

	if err != nil {
		return "", err
	}

	return "successfully marked the location as arrived", nil
}

// CreateCargo is the resolver for the CreateCargo field.
func (r *mutationResolver) CreateCargo(ctx context.Context, name string, origin string, maxCapacity model.CapacityInput) (string, error) {
	_, err := r.cargoService.CreateCargo(ctx, &genproto.CreateCargoRequest{
		Name:   name,
		Origin: origin,
		MaxCapacity: &genproto.Capacity{
			Weight: maxCapacity.Weight,
			Volume: maxCapacity.Volume,
		},
	})

	if err != nil {
		return "failed to create cargo", err
	}

	return "successfully created cargo", nil
}

// AssignCarrier is the resolver for the AssignCarrier field.
func (r *mutationResolver) AssignCarrier(ctx context.Context, cargoID string, carrierIds []string) (string, error) {
	_, err := r.cargoService.AssignCarrier(ctx, &genproto.AssignCarrierRequest{
		CargoId:    cargoID,
		CarrierIds: carrierIds,
	})

	if err != nil {
		return "failed to assign carrier", err
	}

	return "successfully assigned carrier to cargo", nil
}

// AssignRoute is the resolver for the AssignRoute field.
func (r *mutationResolver) AssignRoute(ctx context.Context, cargoID string, itineraries []*model.ItineraryInput) (string, error) {
	itineraryProto := make([]*genproto.Itinerary, len(itineraries))
	for i, it := range itineraries {
		itineraryProto[i] = &genproto.Itinerary{
			Location:             it.LocationID,
			EstimatedTimeArrival: timestamppb.New(it.EstimatedTimeArrival),
		}
	}

	_, err := r.cargoService.AssignRoute(ctx, &genproto.AssignRouteRequest{
		CargoId:     cargoID,
		Itineraries: itineraryProto,
	})

	if err != nil {
		return "failed to assign route", err
	}

	return "successfully assigned route to cargo", nil
}

// GetMatchingCargos is the resolver for the GetMatchingCargos field.
func (r *queryResolver) GetMatchingCargos(ctx context.Context, origin string, destination string) ([]*model.Cargo, error) {
	result, err := r.cargoService.GetMatchingCargos(ctx, &genproto.GetMatchingCargosRequest{
		Origin:      origin,
		Destination: destination,
	})

	if err != nil {
		fmt.Println("panggil")
		return nil, err
	}

	return cargosToGraphResponse(result.Cargos), nil
}

// GetUnroutedCargos is the resolver for the GetUnroutedCargos field.
func (r *queryResolver) GetUnroutedCargos(ctx context.Context, locationID string) ([]*model.Cargo, error) {
	result, err := r.cargoService.GetUnroutedCargos(ctx, &genproto.GetUnroutedCargosRequest{
		LocationId: locationID,
	})

	if err != nil {
		return nil, err
	}

	return cargosToGraphResponse(result.Cargos), nil
}

// FindCargosWithoutCarrier is the resolver for the FindCargosWithoutCarrier field.
func (r *queryResolver) FindCargosWithoutCarrier(ctx context.Context, locationID string) ([]*model.Cargo, error) {
	result, err := r.cargoService.FindCargosWithoutCarrier(ctx, &genproto.FindCargosWithoutCarrierRequest{
		LocationId: locationID,
	})

	if err != nil {
		return nil, err
	}

	return cargosToGraphResponse(result.Cargos), nil
}

// GetIdleCarriers is the resolver for the GetIdleCarriers field.
func (r *queryResolver) GetIdleCarriers(ctx context.Context, locationID string) ([]*model.Carrier, error) {
	result, err := r.cargoService.GetIdleCarriers(ctx, &genproto.GetIdleCarriersRequest{
		LocationId: locationID,
	})

	if err != nil {
		return nil, err
	}

	return carriersToGraphResponse(result.Carriers), nil
}

// Cargo returns generated.CargoResolver implementation.
func (r *Resolver) Cargo() generated.CargoResolver { return &cargoResolver{r} }

// Carrier returns generated.CarrierResolver implementation.
func (r *Resolver) Carrier() generated.CarrierResolver { return &carrierResolver{r} }

// Itinerary returns generated.ItineraryResolver implementation.
func (r *Resolver) Itinerary() generated.ItineraryResolver { return &itineraryResolver{r} }

type cargoResolver struct{ *Resolver }
type carrierResolver struct{ *Resolver }
type itineraryResolver struct{ *Resolver }
