// Code generated by MockGen. DO NOT EDIT.
// Source: shipment_service.go
//
// Generated by this command:
//
//	mockgen -source shipment_service.go -destination ../mock/mock_external_service.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/mproyyan/goparcel/internal/shipments/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLocationService is a mock of LocationService interface.
type MockLocationService struct {
	ctrl     *gomock.Controller
	recorder *MockLocationServiceMockRecorder
	isgomock struct{}
}

// MockLocationServiceMockRecorder is the mock recorder for MockLocationService.
type MockLocationServiceMockRecorder struct {
	mock *MockLocationService
}

// NewMockLocationService creates a new mock instance.
func NewMockLocationService(ctrl *gomock.Controller) *MockLocationService {
	mock := &MockLocationService{ctrl: ctrl}
	mock.recorder = &MockLocationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationService) EXPECT() *MockLocationServiceMockRecorder {
	return m.recorder
}

// ResolveAddress mocks base method.
func (m *MockLocationService) ResolveAddress(ctx context.Context, zipcode string) (*domain.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAddress", ctx, zipcode)
	ret0, _ := ret[0].(*domain.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAddress indicates an expected call of ResolveAddress.
func (mr *MockLocationServiceMockRecorder) ResolveAddress(ctx, zipcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAddress", reflect.TypeOf((*MockLocationService)(nil).ResolveAddress), ctx, zipcode)
}
