// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go
//
// Generated by this command:
//
//	mockgen -source user_service.go -destination ../mock/mock_external_service.go -package mock
//

// Package mock is a generated GoMock package.
package mock
